data:
  file_name: 样机_芯片2_温昱婷_20240618.xlsx
  data_sheet:
    - 重建光谱
    - 光源光谱
  data_transpose: True
  data_start_row: 2 
  target_sheet: 理化值
  target_column: 水分
  task_type: regression

plot_data: True
plot_results: True

preprocess: move_avg
# preprocess_params:
#   window_size: 11

feature_selection: pca
feature_params:
  # n_features: [10, 20, 30, 50]
  # n_components: [10, 15, 20, 30, 50]
  n_components: [10, 15, 20, 30]
  # n_components: 100

# feature_selection: select_from_model

data_split: ks
split_params:
  # test_size: [0.2, 0.3]
  test_size: 0.3

model: PLS
# model_params:
#   n_components: [1, 2, 3]
  # n_components: [1, 2, 3, 4, 5]

# model: SVR